---
title: "EF tasks markdown 2020"
author: "Christoph Voelter"
date: "January 26, 2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())
library(lme4)
library(readr)
library(tidyverse)
library(sjPlot)
library(ggthemes)
library(gridExtra)
library(ggpubr)
library(corrr)
library(reshape2)
#library(Hmisc)
#library("PerformanceAnalytics")
source("C:/Users/voelterc/R/R scripts/Roger/diagnostic_fcns.r")
source("C:/Users/voelterc/R/R scripts/Roger/glmm_stability.r")
source("C:/Users/voelterc/R/R scripts/Roger/boxplotteR.r")
source("C:/Users/voelterc/R/R scripts/Roger/boot_glmm.r")
source("C:/Users/voelterc/R/R scripts/Roger/corr_exact.r")
#load(file ="mm1_mult_poss.RData")
#readRDS(file ="multpos_model.rds")
```

```{r loading data, include = FALSE}
WM.data <- read.csv(file="WM_task_individual_corr2020.csv")
Inh.data <- read.csv(file="Inh_task_individual_corr2020.csv")
Shifting.data <- read.csv(file="Shifting_task_individual_corr2020.csv")

```

```{r include=FALSE}
str(WM.data)

WM.data_pos<-WM.data %>% 
  select(-grid_numberAttempts, -Updating2_P1.mistakes)%>%
  mutate(Updating_P1.mistakes=Updating_P1.mistakes*(-1)) %>% 
  mutate(Updating_4Boxes.Mistakes=Updating_4Boxes.Mistakes*(-1)) %>% 
  mutate(Updating_5Boxes.Mistakes=Updating_5Boxes.Mistakes *(-1)) %>%
  mutate(updatingTraining4_first4=updatingTraining4_first4 *(-1)) %>%
  mutate(updatingTraining5_first5_2=updatingTraining5_first5_2*(-1)) %>%
  mutate(updating_P1P2_first4=updating_P1P2_first4*(-1)) %>%
  #mutate(Updating2_P1.mistakes=Updating2_P1.mistakes*(-1)) %>% 
  mutate(Boxes_P1.mistakes=Boxes_P1.mistakes*(-1)) %>% 
  mutate(boxes_mistakes=boxes_mistakes *(-1)) %>% 
  mutate(Grid_Distance=Grid_Distance*(-1))
  
summary(WM.data_pos )
```


## Summary
  


```{r preparing data for correlation, include=FALSE}

#Join DVs together
EF_task_data <- WM.data  %>% 
  full_join(Inh.data)%>%
  full_join(Shifting.data)

summary(EF_task_data)

```




***  

## Plotting correlations
```{r include=FALSE}
d <- correlate(EF_task_data [-1], method="spearman")
```

```{r include=FALSE}
#jpeg(file="WM_corrplot.jpeg", width=3800, height=1000, res=300)
#pdf(file="WM_corrplot.pdf", width=10, height=4)
d %>%
  shave(upper = TRUE) %>%
  rplot(print_cor = TRUE, colors = c("red", "green"), shape = 16) 
#dev.off()
#rcorr(as.matrix(WM_task_individual[-1]), type="spearman")

#chart.Correlation(WM_task_individual[-1], histogram=TRUE, pch=19, method = "spearman")
```

```{r echo=FALSE}
# Get upper triangle of the correlation matrix
  get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
  }

EF_task_data2<-EF_task_data %>%
  select(ED, CD,  shelf_switches, Shifting.tray.correct.S2,Inh.grid.correct1, Inh.cylinders.correct1, Inh.boxes.correct1, Grid_Distance,boxes_mistakes,Updating_P1.mistakes )
#str(EF_task_data2)

#EF_task_data_select <- EF_task_data  %>% 
 # select(-Shifting.tray.correct,-Shifting.tray.correct.S1,#-SD, -SR, -CD, -ID,
  #       -Shifting.shelf.correct, -shelf_switching_mistakes )

  
cormat <- round(cor(EF_task_data2[-1], method="pearson", use = "pairwise.complete.obs"),2)
upper_tri <- get_upper_tri(cormat)
melted_cormat=melt(cormat, na.rm = TRUE)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()+
  geom_text(aes(Var2, Var1, label = value), color = "black", size = 2) +
 scale_fill_gradient2(low = "blue", high = "red", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name=" Pearson Correlation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 8, hjust = 1))+
  labs(x="",y="")+
 coord_fixed()

```


```{r echo=FALSE, warning=FALSE}




library(ggcorrplot)
corr <- cor(EF_task_data2 [-1])
p.mat <- cor_pmat(EF_task_data2 [-1])
ggcorrplot(cormat, hc.order = TRUE,
    type = "lower", p.mat =p.mat, lab=FALSE, sig.level = 0.1)

```
```{r echo=FALSE}
knitr::knit_exit()
```

```{r include=FALSE}
write.csv(EF_task_data , file = "EF_task_individual_corr.csv", row.names=FALSE)
```